version: "3.8"

services:
  todotelegrambot:
    image: todotelegrambot
    build:
      context: .
      dockerfile: ./Dockerfile
    command: [ "pwd" ]
    volumes:
      - ./app.py:/app/app.py
      - ./.env:/app/.env
    depends_on:
      - mongodb
  webservercert:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginxcert/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www/:/etc/nginx/html/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  webserver:
    image: nginx:latest
    ports:
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./datawww/:/etc/nginx/html/
  certbot:
    image: certbot/certbot:latest
    env_file:
      - .env
    command: certonly --webroot --email yellow444@gmail.com --webroot-path /var/www/certbot/ --non-interactive --agree-tos -d ${DOMAIN_NAME}
    # --dry-run
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    # command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
