version: "3.8"

services:
  todotelegrambot:
    image: todotelegrambot
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["pwd"]
    volumes:
      - ./app.py:/app/app.py
      - ./.env:/app/.env
    depends_on:
      - webserver
  # webserver:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  #     # - datawww:/etc/nginx/html/:ro
  #     - ./certbot/www/:/etc/nginx/html/:ro
  #     # - datawww:/var/www/certbot:ro
  #     - ./certbot/www:/var/www/certbot/:ro      
  #     # - datassl:/etc/nginx/ssl:ro
  #     - ./certbot/conf/:/etc/nginx/ssl/:ro
  #   depends_on:
  #     - certbot
  # certbot:
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --email yellow444@gmail.com --webroot-path /var/www/certbot/ --non-interactive --agree-tos -d broadband-188-255-24-92.ip.moscow.rt.ru 
  #   volumes:
  #     # - datawww:/var/www/certbot:rw
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     # - datassl:/etc/letsencrypt/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

# --dry-run

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    # logging:
    #   driver: "none"
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: admin
      # MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./mongo-data:/data/db
    # ports:
    #   - 27017:27017

# volumes:
#   datassl:
#     driver: local
#     driver_opts:
#       type: "tmpfs"
#       device: "tmpfs"
#       o: "size=256m,uid=1000"
#   datawww:
#     driver: local
#     driver_opts:
#       type: "tmpfs"
#       device: "tmpfs"
#       o: "size=256m,uid=1000"
    # external: true
