apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: telegramcalendar
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: telegramcalendar-mongo  # This should match the labels in the StatefulSet
  type: ClusterIP  # Default service type; change to NodePort or LoadBalancer if needed
